const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const handlers = {}, fields = new Map(), calls = [];
const field = selector => {
    if (!fields.has(selector)) fields.set(selector, { textContent: '', focus() {}, setAttribute(name, value) { this[name] = value; } });
    return fields.get(selector);
};
let markup = '', renderCount = 0;
const matchButton = { disabled: true };
const input = { value: '', focus() {} };
let activeForm;
const root = { get innerHTML() { return markup; }, set innerHTML(value) {
    markup = value; renderCount++;
    const formType = markup.match(/data-form="([^"]+)"/)?.[1];
    input.value = markup.match(/value="([^"]*)"/)?.[1] || '';
    activeForm = formType ? { dataset: { form: formType },
        querySelector: selector => selector === 'input' ? input : matchButton } : null;
},
    hidden: false, querySelector: selector => selector === '.ui-match-result' && !markup.includes('ui-match-result') ? null : field(selector),
    querySelectorAll: selector => selector === 'form' && activeForm ? [activeForm] : [],
    addEventListener: (event, handler) => handlers[event] = handler };
const body = { classList: { add() {}, remove() {}, toggle() {} }, append(script) { assert.equal(script.src, 'app.js'); } };
const saved = new Map(), styles = new Map();
const context = { document: { querySelector: () => root, body, createElement: () => ({}),
        documentElement: { style: { setProperty: (key, value) => styles.set(key, value) } } },
    location: { search: '' }, URLSearchParams, localStorage: { getItem: key => saved.get(key), setItem: (key, value) => saved.set(key, value) },
    FormData: class { constructor(form) { this.data = form.data; } get(key) { return this.data[key]; } },
    window: { coreGame: { match: (...args) => calls.push(args), send: command => calls.push(command), leave: () => calls.push('leave') } } };
vm.runInNewContext(fs.readFileSync('client/pointer-settings.js', 'utf8'), context);
vm.runInNewContext(fs.readFileSync('client/key-settings.js', 'utf8'), context);
vm.runInNewContext(fs.readFileSync('client/job-ui.js', 'utf8'), context);
vm.runInNewContext(fs.readFileSync('client/sound.js', 'utf8'), { ...context, window: Object.assign(context.window, { addEventListener() {} }) });
vm.runInNewContext(fs.readFileSync('client/menu-ui.js', 'utf8'), context);
const submit = (form, data = {}) => handlers.submit({ preventDefault() {}, target: { dataset: { form }, data } });
const click = (action, slot) => handlers.click({ target: { closest: selector => selector === ".job-panel" ? (action === "job" ? {} : null) : ({ dataset: { action, slot, job: slot } }) } });
function edit(value) { input.value = value; handlers.input({ target: input }); }
function assertEmptyGating(label, valid = '入力') {
    for (const value of ['', '　 ']) {
        edit(value);
        assert(matchButton.disabled, `${label}: blank and whitespace-only inputs disable confirmation`);
    }
    edit(valid);
    assert(!matchButton.disabled, `${label}: typing enables confirmation`);
}
function assertInputSurvivesReconnects(label, hasMatchButton = false) {
    const before = renderCount;
    for (let attempt = 0; attempt < 3; attempt++) {
        context.window.coreMenu.disconnected();
        if (hasMatchButton) assert(matchButton.disabled, `${label}: disable matching while disconnected`);
        context.window.coreMenu.connected();
        if (hasMatchButton) assert(!matchButton.disabled, `${label}: enable matching after reconnect`);
        context.window.coreMenu.status('connection error');
    }
    assert.equal(renderCount, before, `${label}: preserve the input DOM, draft, focus, selection and composition`);
}
assert.match(root.innerHTML, /ゲストプレイヤー名/);
assert.match(root.innerHTML, /placeholder="ゲストプレイヤー名"/);
assert.match(root.innerHTML, /<button>決定<\/button>/);
assert.doesNotMatch(root.innerHTML, /<label|\brequired\b/);
assert(matchButton.disabled, 'initial empty name disables confirmation');
assertEmptyGating('initial player name');
assertInputSurvivesReconnects('initial player name');
submit('name', { name: ' ' });
assert.doesNotMatch(root.innerHTML, /ui-message/);
submit('name', { name: '<Host>' });
assert.match(root.innerHTML, /クイックマッチ/);
assert.match(root.innerHTML, />合言葉</);
assert.doesNotMatch(root.innerHTML, /ルーム作成|ルーム検索/);
click('phrase');
assert.doesNotMatch(root.innerHTML, /<h2>/, 'passphrase menu has no heading');
assert.match(root.innerHTML, /ルーム作成/);
assert.match(root.innerHTML, /ルーム検索/);
click('create');
assert.doesNotMatch(root.innerHTML, /<h2>/, 'creation form has no heading');
assert.match(root.innerHTML, /name="password"[^>]*placeholder="合言葉"/);
assert.doesNotMatch(root.innerHTML, /<label|\brequired\b/);
assert.doesNotMatch(root.innerHTML, /visibility|公開/);
context.window.coreMenu.connected();
assert(matchButton.disabled, 'connecting does not enable an empty password');
assertEmptyGating('create room password');
assertInputSurvivesReconnects('create room password', true);
submit('create', { password: ' ' });
assert.equal(calls.length, 0, 'blank input quietly stays on the form');
submit('create', { password: ' 合言葉<&> ' });
assert(matchButton.disabled, 'disable matching while the request is pending');
submit('create', { password: 'duplicate' });
assert.deepEqual(calls, [['create', '合言葉<&>', '<Host>']]);
assert.doesNotMatch(root.innerHTML, /ui-members/, 'must wait for server response');
const state = { phase: 'lobby', privateRoom: true, roomOwnerId: 'p1', allReady: true,
    players: [1, 2, 3, 4].map(i => ({ id: 'p' + i, name: i === 1 ? '<Host>' : 'CPU', human: i === 1, ready: false })) };
context.window.coreMenu.snapshot(state, 'p1');
assert.match(root.innerHTML, /&lt;Host&gt;<\/strong><span>host<\/span>/);
assert.doesNotMatch(root.innerHTML, / · HOST/);
assert.doesNotMatch(root.innerHTML, /CORE DEFENSE|クイックマッチ|合言葉|ホスト設定|data-action="cpu"|空席|CPU/);
assert.equal((root.innerHTML.match(/class="room-member/g) || []).length, 1);
assert.doesNotMatch(root.innerHTML, /data-action="start" disabled/, 'host can start with automatic CPU fill');
assert.match(root.innerHTML, /data-action="toggle-job"[^>]*>ジョブ:ヒーラー<\/button>/);
assert.match(root.innerHTML, /id="job-panel"[^>]*hidden/);
assert(root.innerHTML.indexOf('data-action="start"') < root.innerHTML.indexOf('data-action="toggle-job"'));
assert(root.innerHTML.indexOf('data-action="toggle-job"') < root.innerHTML.indexOf('data-action="leave"'));
click('toggle-job');
assert.equal(field('#job-panel').hidden, false);
const beforeOutside = calls.length;
handlers.click({target:{closest:()=>null}});
assert.equal(field('#job-panel').hidden, true);
assert.equal(calls.length, beforeOutside);
click('toggle-job');
assert.equal((root.innerHTML.match(/data-action="job"/g) || []).length, 4);
assert.match(root.innerHTML, /data-job="healer" aria-pressed="true"/);
const jobButtons = root.innerHTML.match(/<button[^>]*data-action="job"[^>]*>[\s\S]*?<\/button>/g);
for (const markup of jobButtons) assert.match(markup, /^<button[^>]*>[^<>]+<\/button>$/, 'job buttons contain only the name');
assert.match(root.innerHTML, /class="job-detail"[\s\S]*ダウンした味方を素早くリバイブする/);
field('.job-list').scrollTop = 220;
click('job', 'scout'); assert.equal(calls.at(-1), 'JOB:scout');
assert.equal(field('#job-panel').hidden, false, 'choosing a job keeps the panel open');
state.players[0].job = 'scout';
context.window.coreMenu.snapshot(state, 'p1');
assert.match(root.innerHTML, /data-job="scout" aria-pressed="true"/);
assert.match(root.innerHTML, /ジョブ:スカウト/);
assert.equal(field('.job-list').scrollTop, 220, 'selection preserves catalogue scroll position');
assert.match(root.innerHTML, /class="job-detail"[\s\S]*ダッシュが少し速く/);
assert.doesNotMatch(root.innerHTML, /ダウンした味方を素早くリバイブする/);
assert.doesNotMatch(root.innerHTML, /\+15%|\+60%|<dl>|再使用|蘇生 2秒/);
const futureJobs = Object.fromEntries(Array.from({length: 30}, (_, i) => ['job-' + i, {name: 'JOB ' + i, description: 'Ability ' + i}]));
const futureMarkup = context.window.JobUI.render('job-24', false, futureJobs);
assert.equal((futureMarkup.match(/data-action="job"/g) || []).length, 30);
assert.match(futureMarkup, /data-job="job-24" aria-pressed="true"/);
assert.match(futureMarkup, /Ability 24/);
assert.doesNotMatch(futureMarkup, /Ability (?:0|23|25)<\/p>/);
click('start'); assert.equal(calls.at(-1), 'START');
assert.equal(field('#job-panel').hidden, true, 'start closes the panel while preserving its action');
const appSource = fs.readFileSync('client/app.js', 'utf8');
const sendStart = appSource.indexOf('function send(message)');
const sendEnd = appSource.indexOf('\nfunction ', sendStart + 1);
const originalSend = context.window.coreGame.send;
for (const debugMode of [false, true]) {
    const sent = [];
    const gameContext = vm.createContext({ DEBUG_MODE: debugMode, WebSocket: { OPEN: 1 },
        socket: { readyState: 1, send: message => sent.push(message) },
        nextInputSequence: 1, pendingInputs: [] });
    vm.runInContext(appSource.slice(sendStart, sendEnd), gameContext);
    context.window.coreGame.send = gameContext.send;
    for (const phase of ['lobby', 'won', 'lost']) {
        context.window.coreMenu.snapshot({ ...state, phase }, 'p1');
        click('start');
        assert.equal(sent.at(-1), `INPUT:${sent.length}:START${debugMode ? ':DEBUG' : ''}`,
            `${phase}: the visible menu must send the debug flag only in debug mode`);
    }
}
context.window.coreGame.send = originalSend;
context.window.coreMenu.snapshot({ ...state, phase: 'preparing' }, 'p1');
assert(root.hidden);
state.privateRoom = false;
state.players[1].human = true; state.players[1].name = 'Guest'; state.allReady = false;
context.window.coreMenu.snapshot(state, 'p1');
assert(!root.hidden);
assert.match(root.innerHTML, /data-action="start" disabled/, 'host must wait for human guests');
context.window.coreMenu.snapshot(state, 'p2');
assert.doesNotMatch(root.innerHTML, /data-action="start"|data-action="cpu"/);
click('toggle-job');
click('ready'); assert.equal(calls.at(-1), 'ROOM_READY:1');
assert.equal(field('#job-panel').hidden, true, 'ready closes the panel and still changes readiness');
state.players[1].ready = true; state.allReady = true;
context.window.coreMenu.snapshot(state, 'p1');
assert.match(root.innerHTML, /room-member ready[\s\S]*準備完了/);
state.roomOwnerId = 'p2';
context.window.coreMenu.snapshot(state, 'p2');
assert.match(root.innerHTML, /Guest<\/strong><span>host<\/span>/);
assert.match(root.innerHTML, /data-action="start"/);
context.window.coreMenu.disconnected('切断されました');
assert.match(root.innerHTML, /data-action="start" disabled/);
click('leave'); assert.equal(calls.at(-1), 'leave');
context.window.coreMenu.connected();
const beforeQuick = calls.length;
click('quick');
assert.equal(calls.length, beforeQuick + 1, 'one click immediately starts matching');
assert.match(root.innerHTML, /メインメニュー/);
assert.doesNotMatch(root.innerHTML, /検索して参加|空いているルームへ参加/);
click('quick');
assert.equal(calls.length, beforeQuick + 1, 'ignore duplicate clicks while matching');
assert.deepEqual(calls.at(-1), ['quick', '', '<Host>']);
context.window.coreMenu.status('満員'); context.window.coreMenu.rejected();
assert.doesNotMatch(root.innerHTML, /<h2>|クイックマッチ/);
assert.match(root.innerHTML, /接続できません/);
assert.doesNotMatch(root.innerHTML, /再試行/);
assert.equal((root.innerHTML.match(/<button/g) || []).length, 1);
click('home');
assert.doesNotMatch(root.innerHTML, /接続できません/);
const originalMatch = context.window.coreGame.match;
context.window.coreGame.match = () => { throw new Error('サーバーへの接続を待ってください'); };
click('quick');
assert.match(root.innerHTML, /接続できません/);
assert.doesNotMatch(root.innerHTML, /ui-message|サーバーへの接続を待ってください/);
click('home');
context.window.coreGame.match = originalMatch;
click('quick');
context.window.coreMenu.disconnected('ルーム一覧から切断されました。再接続します…');
assert.match(root.innerHTML, /接続できません/);
assert.doesNotMatch(root.innerHTML, /ルーム一覧から切断|ui-message/);
click('home');
context.window.coreMenu.connected();
click('phrase'); click('search');
assert.doesNotMatch(root.innerHTML, /<h2>/, 'search heading is replaced by results');
const result = field('.ui-match-result');
assert.equal(result.textContent, '', 'result space is empty before searching');
assert.match(root.innerHTML, />決定<\/button>/);
assert.doesNotMatch(root.innerHTML, /検索して参加|<label|\brequired\b/);
assert(matchButton.disabled, 'search starts with disabled confirmation');
assertEmptyGating('search room password');
assertInputSurvivesReconnects('search room password', true);
const beforeRejection = renderCount;
context.window.coreMenu.phrase = '合言葉';
context.window.coreMenu.rejected();
assert.equal(renderCount, beforeRejection, 'preserve search password when room entry is rejected');
context.window.coreMenu.connected();
const error = '参加できるルームが見つかりません。合言葉・満員・プレイ中でないか確認してください';
context.window.coreMenu.status(error);
assert.equal(result.textContent, '見つかりませんでした');
assert(!result.hidden);
assert.equal(renderCount, beforeRejection, 'results do not replace the input DOM');
context.window.coreMenu.connected();
assert.equal(result.textContent, '見つかりませんでした', 'reconnection preserves the result');
edit('別の合言葉');
assert.equal(result.textContent, '', 'editing clears the old result');
submit('search', { password: '別の合言葉' });
assert.equal(result.textContent, '検索中…');
assert(!result.hidden);
assert(matchButton.disabled);
context.window.coreMenu.status('<接続エラー>');
assert.equal(result.textContent, '<接続エラー>', 'errors are rendered as text');
assert(!matchButton.disabled, 'failed search allows retry');
submit('search', { password: '別の合言葉' });
context.window.coreMenu.disconnected();
assert.equal(result.textContent, '接続できません', 'disconnection ends the searching message');
assert(matchButton.disabled);
context.window.coreMenu.connected();
click('phrase');
assert.doesNotMatch(root.innerHTML, /参加できるルームが見つかりません/);
click('create');
assert.doesNotMatch(root.innerHTML, /参加できるルームが見つかりません/);
assert.equal(result.textContent, '', 'creation starts with no stale feedback');
edit('新しい合言葉');
const beforeCreateError = renderCount;
submit('create', { password: '新しい合言葉' });
assert.equal(result.textContent, '作成中…');
assert(matchButton.disabled);
context.window.coreMenu.status('その合言葉は使用中です');
assert.equal(result.textContent, 'その合言葉は使用中です');
assert(!matchButton.disabled, 'creation errors allow retry');
edit('別の合言葉');
assert.equal(result.textContent, '', 'editing clears creation errors');
submit('create', { password: '別の合言葉' });
context.window.coreMenu.disconnected();
assert.equal(result.textContent, '接続できません', 'creation shows connection failures like search');
assert(matchButton.disabled);
context.window.coreMenu.rejected();
assert.match(root.innerHTML, /data-form="create"/, 'rejected entry stays on creation');
assert.equal(renderCount, beforeCreateError, 'creation errors preserve input DOM and draft');
assert.equal(input.value, '別の合言葉');
context.window.coreMenu.connected();
assert(!matchButton.disabled);
assert.equal(result.textContent, '接続できません', 'reconnection preserves the creation error');
click('phrase'); click('search');
assert.equal(result.textContent, '', 'reopening search clears its previous result');
click('home'); click('settings');
assert.match(root.innerHTML, /name="volume"[^>]*value="100"/);
handlers.input({ target: { name: 'volume', value: '35' } });
assert.equal(context.window.coreAudio.getVolume(), .35);
assert.equal(field('#volume-value').textContent, '35%');
assert.equal(saved.get('core-defense-volume'), '0.35');
assert.match(root.innerHTML, /name="medkit-key"[^>]*value="H"/);
const medkitInput = { name: 'medkit-key', value: 'H' };
handlers.keydown({ target: medkitInput, key: 'q', preventDefault() {} });
assert.equal(medkitInput.value, 'Q');
assert.equal(saved.get('core-defense-medkit-key'), 'q');
handlers.keydown({ target: medkitInput, key: 'w', preventDefault() {} });
assert.equal(medkitInput.value, 'Q');
assert.equal(field('#medkit-key-status').textContent, 'このキーは使用できません');
assert.match(root.innerHTML, /type="color" name="pointer-color" value="#0078ff"/);
assert.match(root.innerHTML, /type="range" name="pointer-size"[^>]*value="6"/);
handlers.input({ target: { name: 'pointer-color', value: '#ff9900' } });
handlers.input({ target: { name: 'pointer-size', value: '20' } });
assert.equal(styles.get('--pointer-color'), '#ff9900');
assert.equal(styles.get('--pointer-size'), '20px');
assert.equal(field('#pointer-size-value').textContent, '20px');
assert.deepEqual(JSON.parse(saved.get('core-defense-pointer')), { color: '#ff9900', size: 20, shape: 'dot' });
click('home'); click('settings');
assert.match(root.innerHTML, /name="pointer-color" value="#ff9900"/);
assert.match(root.innerHTML, /name="pointer-size"[^>]*value="20"/);
assert(!matchButton.disabled, 'saved name enables confirmation even without a connection');
assertEmptyGating('saved player name settings', '<Host>');
assertInputSurvivesReconnects('saved player name settings');
assert.doesNotMatch(root.innerHTML, /参加できるルームが見つかりません/);
context.window.coreMenu.status(error);
submit('name', { name: 'Host' });
assert.doesNotMatch(root.innerHTML, /参加できるルームが見つかりません/);
console.log('Live menu passed: navigation, server requests, snapshots, permissions, disconnect, gameplay');
context.window.coreMenu.phrase = 'private phrase';
context.window.coreMenu.exited();
assert.equal(root.hidden, false);
assert.equal(context.window.coreMenu.phrase, '');
assert.match(root.innerHTML, /data-action="quick"/);

click('settings');
assert.match(root.innerHTML, /name="pointer-shape"/);
handlers.input({ target: { name: 'pointer-shape', value: 'cross' } });
assert.equal(JSON.parse(saved.get('core-defense-pointer')).shape, 'cross');
for (const phase of ['won', 'lost']) {
    context.window.coreMenu.snapshot({ ...state, phase }, 'p1', true);
    assert(root.hidden, 'result delay keeps the game area visible');
    context.window.coreMenu.snapshot({ ...state, phase }, 'p1', false);
    assert(!root.hidden, 'result menu appears after the delay');
}
