const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const handlers = {}, fields = new Map(), calls = [];
const field = selector => {
    if (!fields.has(selector)) fields.set(selector, { textContent: '', focus() {} });
    return fields.get(selector);
};
const root = { innerHTML: '', hidden: false, querySelector: field, querySelectorAll: () => [],
    addEventListener: (event, handler) => handlers[event] = handler };
const body = { classList: { add() {}, remove() {}, toggle() {} }, append(script) { assert.equal(script.src, 'app.js'); } };
const context = { document: { querySelector: () => root, body, createElement: () => ({}) },
    location: { search: '' }, URLSearchParams, localStorage: { getItem() {}, setItem() {} },
    FormData: class { constructor(form) { this.data = form.data; } get(key) { return this.data[key]; } },
    window: { coreGame: { match: (...args) => calls.push(args), send: command => calls.push(command), leave: () => calls.push('leave') } } };
vm.runInNewContext(fs.readFileSync('client/menu-ui.js', 'utf8'), context);
const submit = (form, data = {}) => handlers.submit({ preventDefault() {}, target: { dataset: { form }, data } });
const click = (action, slot) => handlers.click({ target: { closest: () => ({ dataset: { action, slot } }) } });
assert.match(root.innerHTML, /ゲストプレイヤー名/);
submit('name', { name: ' ' });
assert.match(field('#ui-message').textContent, /入力/);
submit('name', { name: '<Host>' });
assert.match(root.innerHTML, /クイックマッチ/);
assert.match(root.innerHTML, />合言葉</);
assert.doesNotMatch(root.innerHTML, /ルーム作成|ルーム検索/);
click('phrase');
assert.match(root.innerHTML, /ルーム作成/);
assert.match(root.innerHTML, /ルーム検索/);
click('create');
assert.match(root.innerHTML, /name="password"[^>]*required/);
assert.doesNotMatch(root.innerHTML, /visibility|公開/);
context.window.coreMenu.connected();
submit('create', { password: ' 合言葉<&> ' });
submit('create', { password: 'duplicate' });
assert.deepEqual(calls, [['create', '合言葉<&>', '<Host>']]);
assert.doesNotMatch(root.innerHTML, /ui-members/, 'must wait for server response');
const state = { phase: 'lobby', privateRoom: true, roomOwnerId: 'p1', allReady: false, cpuSlots: [],
    players: [1, 2, 3, 4].map(i => ({ id: `p${i}`, name: i === 1 ? '<Host>' : 'CPU', human: i === 1, ready: false })) };
context.window.coreMenu.snapshot(state, 'p1');
assert.match(root.innerHTML, /合言葉&lt;&amp;&gt;/);
assert.match(root.innerHTML, /&lt;Host&gt;/);
assert.match(root.innerHTML, /ホスト設定/);
assert.match(root.innerHTML, /data-action="start" disabled/);
click('cpu', '2');
assert.equal(calls.at(-1), 'ROOM_CPU:2');
assert.doesNotMatch(root.innerHTML, />削除</, 'wait for authoritative CPU update');
state.cpuSlots = [2, 3, 4]; state.allReady = true;
context.window.coreMenu.snapshot(state, 'p1');
assert.match(root.innerHTML, />削除</);
click('start'); assert.equal(calls.at(-1), 'START');
context.window.coreMenu.snapshot({ ...state, phase: 'preparing' }, 'p1');
assert(root.hidden);
state.privateRoom = false;
context.window.coreMenu.snapshot(state, 'p1');
assert(!root.hidden);
assert.match(root.innerHTML, /クイックマッチ/);
assert.match(root.innerHTML, /ホスト設定/);
state.players[1].human = true;
context.window.coreMenu.snapshot(state, 'p2');
assert.doesNotMatch(root.innerHTML, /data-action="cpu"|ホスト設定/);
click('ready'); assert.equal(calls.at(-1), 'ROOM_READY:1');
state.roomOwnerId = 'p2';
context.window.coreMenu.snapshot(state, 'p2');
assert.match(root.innerHTML, /ホスト設定/);
context.window.coreMenu.disconnected('切断されました');
assert.match(root.innerHTML, /data-action="start" disabled/);
click('leave'); assert.equal(calls.at(-1), 'leave');
context.window.coreMenu.connected();
click('quick'); submit('quick');
assert.deepEqual(calls.at(-1), ['quick', '', '<Host>']);
context.window.coreMenu.status('満員'); context.window.coreMenu.rejected();
assert.match(root.innerHTML, /クイックマッチ/);
console.log('Live menu passed: navigation, server requests, snapshots, permissions, disconnect, gameplay');
